# Generated by Django 3.1.6 on 2021-03-31 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20210331_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.FloatField(verbose_name='Количество ингредиента'),
        ),
    ]
