# Generated by Django 3.1.6 on 2021-03-31 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20210331_1858'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('title',), 'verbose_name': 'ингредиент', 'verbose_name_plural': 'ингредиенты'},
        ),
    ]
