# Generated by Django 3.1.6 on 2021-03-31 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20210331_1859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('-pub_date',)},
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название тега'),
        ),
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together={('ingredient', 'amount', 'recipe')},
        ),
    ]
