# Generated by Django 3.1.6 on 2021-03-31 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_auto_20210331_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cook_time',
            field=models.IntegerField(verbose_name='Время приготовления'),
        ),
    ]
