# Generated by Django 3.1.6 on 2021-04-02 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0023_auto_20210402_1801'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredient',
            name='unique_recipe_ingredient',
        ),
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together={('ingredient', 'amount', 'recipe')},
        ),
    ]
