# Generated by Django 3.1.6 on 2021-04-02 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0024_auto_20210402_1832'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together=set(),
        ),
    ]
