# Generated by Django 3.1.6 on 2021-04-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0025_auto_20210402_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.IntegerField(verbose_name='Количество ингредиента'),
        ),
    ]
