# Generated by Django 3.1.6 on 2021-04-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0032_auto_20210403_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='Количество ингредиента'),
        ),
    ]
