# Generated by Django 3.1.6 on 2021-04-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0034_auto_20210403_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(verbose_name='Количество ингредиента'),
        ),
    ]
